#!/usr/bin/env python3
"""
Create automated fix PR for governance drift

This script creates a PR with fixes for detected drift violations.
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def load_drift_report(report_path: str) -> dict[str, Any]:
    """Load drift report."""
    with open(report_path) as f:
        return json.load(f)


def create_pr_branch(branch_name: str) -> bool:
    """Create a new branch for the fix PR."""
    try:
        subprocess.run(["git", "checkout", "-b", branch_name], check=True)
        return True
    except subprocess.CalledProcessError:
        print(f"Failed to create branch {branch_name}")
        return False


def copy_template_file(src: str, dest: str) -> bool:
    """Copy a template file from control plane."""
    src_path = Path(src)
    dest_path = Path(dest)
    
    if not src_path.exists():
        print(f"Template file not found: {src}")
        return False
    
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    dest_path.write_text(src_path.read_text())
    print(f"  ✓ Copied {src} to {dest}")
    return True


def fix_missing_workflows(violations: list[dict[str, Any]]) -> bool:
    """Fix missing workflow violations."""
    fixed = False
    
    for violation in violations:
        if violation["type"] == "missing-workflow":
            file_path = violation["file"]
            template = f".github/workflows/{Path(file_path).name}"
            
            if copy_template_file(template, file_path):
                subprocess.run(["git", "add", file_path])
                fixed = True
    
    return fixed


def create_fix_commit(drift_report: dict[str, Any]) -> bool:
    """Create a commit with the fixes."""
    violations = drift_report.get("violations", [])
    
    commit_msg = f"""Fix governance drift

Automated fix for {len(violations)} violation(s):
"""
    
    for violation in violations:
        commit_msg += f"- {violation['type']}: {violation['message']}\n"
    
    commit_msg += f"\nTimestamp: {datetime.now(timezone.utc).isoformat()}"
    commit_msg += "\nGenerated by: autopilot-auditor"
    
    try:
        subprocess.run(["git", "commit", "-m", commit_msg], check=True)
        return True
    except subprocess.CalledProcessError:
        print("Failed to create commit")
        return False


def create_pr(branch_name: str, drift_report: dict[str, Any]) -> bool:
    """Create a pull request using gh CLI."""
    violations = drift_report.get("violations", [])
    
    pr_title = f"[Autopilot] Fix governance drift ({len(violations)} violation(s))"
    
    pr_body = f"""## Automated Governance Fix

This PR was automatically created by the autopilot auditor to fix detected drift.

### Violations Fixed

"""
    
    for violation in violations:
        pr_body += f"- **{violation['type']}**: {violation['message']}\n"
        if "file" in violation:
            pr_body += f"  - File: `{violation['file']}`\n"
    
    pr_body += f"""

### Drift Report

- **Repository**: {drift_report['repository']}
- **Timestamp**: {drift_report['timestamp']}
- **Policies**: {', '.join(drift_report['policies'])}

### Review Checklist

- [ ] Verify that all fixes are correct
- [ ] Check that no unintended changes were introduced
- [ ] Confirm compliance with governance policies

---

🤖 This PR was generated automatically by the autonomous governance system.
"""
    
    try:
        # Push branch
        subprocess.run(["git", "push", "-u", "origin", branch_name], check=True)
        
        # Create PR using gh CLI
        subprocess.run([
            "gh", "pr", "create",
            "--title", pr_title,
            "--body", pr_body,
            "--label", "autopilot",
            "--label", "governance",
        ], check=True)
        
        return True
    except subprocess.CalledProcessError:
        print("Failed to create PR")
        return False


def main():
    """CLI entry point."""
    if len(sys.argv) < 2:
        print("Usage: create_fix_pr.py <drift_report.json>")
        sys.exit(1)
    
    report_path = sys.argv[1]
    
    print("Loading drift report...")
    drift_report = load_drift_report(report_path)
    
    if not drift_report.get("drift_detected"):
        print("No drift detected, nothing to fix")
        sys.exit(0)
    
    violations = drift_report.get("violations", [])
    print(f"Found {len(violations)} violation(s) to fix")
    
    # Create fix branch
    branch_name = f"autopilot/fix-drift-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}"
    print(f"\nCreating fix branch: {branch_name}")
    
    if not create_pr_branch(branch_name):
        sys.exit(1)
    
    # Apply fixes
    print("\nApplying fixes...")
    fixed = fix_missing_workflows(violations)
    
    if not fixed:
        print("No fixes were applied")
        sys.exit(0)
    
    # Create commit
    print("\nCreating commit...")
    if not create_fix_commit(drift_report):
        sys.exit(1)
    
    # Create PR
    print("\nCreating pull request...")
    if not create_pr(branch_name, drift_report):
        sys.exit(1)
    
    print("\n✅ Fix PR created successfully")


if __name__ == "__main__":
    main()
